#pragma checksum "..\..\..\UI\ControllerWithContextControl.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "CB5AC141CFD94E323019DB2FF39E0A43"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNet.Scaffolding.Mvc.Properties;
using Microsoft.AspNet.Scaffolding.Mvc.UserInterface;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Microsoft.AspNet.Scaffolding.Mvc.UserInterface {
    
    
    /// <summary>
    /// ControllerWithContextControl
    /// </summary>
    public partial class ControllerWithContextControl : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 24 "..\..\..\UI\ControllerWithContextControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox modelTypeComboBox;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\UI\ControllerWithContextControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dataContextComboBox;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\UI\ControllerWithContextControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button dataContextAddButton;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\..\UI\ControllerWithContextControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox useAsyncControllerActions;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\..\UI\ControllerWithContextControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox generateViewsCheckBox;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\UI\ControllerWithContextControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox referenceScriptLibrariesCheckBox;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\UI\ControllerWithContextControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox useLayoutPageCheckBox;
        
        #line default
        #line hidden
        
        
        #line 121 "..\..\..\UI\ControllerWithContextControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox layoutPageFileTextBox;
        
        #line default
        #line hidden
        
        
        #line 126 "..\..\..\UI\ControllerWithContextControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button browseFiles;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/HMVScaffolder;component/ui/controllerwithcontextcontrol.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\UI\ControllerWithContextControl.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.modelTypeComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 2:
            this.dataContextComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 3:
            this.dataContextAddButton = ((System.Windows.Controls.Button)(target));
            return;
            case 4:
            this.useAsyncControllerActions = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 5:
            this.generateViewsCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 6:
            this.referenceScriptLibrariesCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 7:
            this.useLayoutPageCheckBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 8:
            this.layoutPageFileTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.browseFiles = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

